name: C/C++ CI on Windows
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    name: Build NekoAV
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
      # The version to use. Should be a semver range or 'latest'. Or use branch@{branch_name} to select a branch.
        xmake-version: latest
    - name: Configure
      run: xmake f -m debug --test=y -y
    - name: Build
      run: xmake -y
    - name: Run Core Test
      run: xmake run coretest